#!/bin/bash
fasta=$1
effector=/bulk/liu3zhen/research/projects/mini2020/data/effectors/known.effectors.db03.fasta
out=`basename $fasta | sed 's/.fasta//'`
~/software/miniprot/protmap \
	--prot $effector \
	--dna $fasta \

