#!/bin/bash
fasta=$1
effector=/homes/liu3zhen/scripts2/miniprot/protmap/data/Mo.effectors.db03.fasta
out=`basename $fasta | sed 's/.fasta//'`

~/software/miniprot/protmap \
	--prot $effector \
	--dna $fasta \

